version: '3.8'
services:
  nahpet-app:
    image: ghcr.io/anhostfr/nah.pet:latest
    restart: always
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: ${PORT:-3000}
      DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@nahpet-postgres:5432/${DB_NAME}?schema=public'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      OAUTH_CLIENT_ID: '${OAUTH_CLIENT_ID}'
      OAUTH_CLIENT_SECRET: '${OAUTH_CLIENT_SECRET}'
      PUBLIC_MAIN_DOMAIN: '${PUBLIC_MAIN_DOMAIN}'
    depends_on:
      nahpet-postgres:
        condition: service_healthy
    command: sh -c "bunx prisma migrate deploy && bun run build/index.js"
  nahpet-postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - nahpet-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  nahpet-postgres-data:
