version: '3.9'

services:
  db:
    image: postgres:16
    container_name: nahpet-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nahpet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    container_name: nahpet-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/nahpet?schema=public"
      NODE_ENV: production
    command: ["bun", "./build/index.js"]
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: