services:
  nahpet-app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      MAIN_URL: "https://${NAHPET_HOST}"
      PUBLIC_URL: "https://${NAHPET_HOST}"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@nahpet-postgres:5432/${DB_NAME}?schema=public"
    volumes:
      - nahpet-uploads:/uploads/
    depends_on:
      nahpet-postgres:
        condition: service_healthy
    command: sh -c "bunx prisma migrate deploy && bun start"
    networks:
      - dokploy-network
    labels:
      - "dokploy.domain=${NAHPET_HOST}"

  nahpet-postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - nahpet-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  nahpet-postgres-data:
  nahpet-uploads:
